import { GameItem } from '../types/game';
import { BUBBLE_SHOOTER_FALLBACK_PACKAGE } from './bubble-shooter/levels';
import { SWEET_GARDEN_FALLBACK_PACKAGE } from './sweet-garden/levels';
import { SLIDING_PUZZLE_FALLBACK_PACKAGE } from './sliding-puzzle/levels';

export const LOCAL_GAME_CATALOG: GameItem[] = [
  {
    gameId: 'bubble-shooter',
    slug: 'bubble-shooter',
    title: 'Bubble Shooter',
    description: 'Aim, shoot, and pop matching colored bubbles in this classic arcade puzzle challenge!',
    category: 'Puzzle',
    engineType: 'bubble-shooter',
    version: '1.0.0',
    packageVersion: '1.0.0',
    contentVersion: 1,
    isPublished: true,
    isFeatured: true,
    isNew: true,
    downloadSize: '1.8 MB',
    thumbnailUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=400&q=80',
    iconUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=120&q=80',
    isDownloaded: true,
  },
  {
    gameId: 'sweet-garden',
    slug: 'sweet-garden',
    title: 'Sweet Garden',
    description: 'Match delicious fruits, berries, and blooming flowers to clear board goals in this sweet garden match-3 adventure!',
    category: 'Match-3',
    engineType: 'match-3',
    version: '1.0.0',
    packageVersion: '1.0.0',
    contentVersion: 1,
    isPublished: true,
    isFeatured: true,
    isNew: false,
    downloadSize: '2.1 MB',
    thumbnailUrl: 'https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=400&q=80',
    iconUrl: 'https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=120&q=80',
    isDownloaded: true,
  },
  {
    gameId: 'sliding-puzzle',
    slug: 'sliding-puzzle',
    title: 'Sliding Puzzle',
    description: 'Slide numbered tiles into place to form ordered grids. Fast-paced, brain-teasing tile sliding fun!',
    category: 'Brain',
    engineType: 'puzzle',
    version: '1.0.0',
    packageVersion: '1.0.0',
    contentVersion: 1,
    isPublished: true,
    isFeatured: true,
    isNew: true,
    downloadSize: '1.2 MB',
    thumbnailUrl: 'https://images.unsplash.com/photo-1611996575749-79a3a250f948?auto=format&fit=crop&w=400&q=80',
    iconUrl: 'https://images.unsplash.com/photo-1611996575749-79a3a250f948?auto=format&fit=crop&w=120&q=80',
    isDownloaded: true,
  },
  {
    gameId: 'cosmic-pop',
    slug: 'cosmic-pop',
    title: 'Cosmic Pop',
    description: 'Pop galaxy bubbles across neon nebula levels with cosmic combo boosts!',
    category: 'Arcade',
    engineType: 'bubble-shooter',
    version: '1.1.0',
    packageVersion: '1.1.0',
    contentVersion: 2,
    isPublished: true,
    isFeatured: true,
    isNew: true,
    downloadSize: '1.9 MB',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80',
    iconUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=120&q=80',
    isDownloaded: false,
  },
  {
    gameId: 'fruit-blast',
    slug: 'fruit-blast',
    title: 'Fruit Blast',
    description: 'Blast juicy tropical fruits in cascade match-3 combos to unlock high scores!',
    category: 'Match-3',
    engineType: 'match-3',
    version: '1.2.0',
    packageVersion: '1.2.0',
    contentVersion: 2,
    isPublished: true,
    isFeatured: false,
    isNew: true,
    downloadSize: '2.4 MB',
    thumbnailUrl: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&w=400&q=80',
    iconUrl: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&w=120&q=80',
    isDownloaded: false,
  },
  {
    gameId: 'number-slide',
    slug: 'number-slide',
    title: 'Number Slide 15',
    description: 'Classic 15-tile numerical slider challenge. Test your speed and strategy!',
    category: 'Brain',
    engineType: 'puzzle',
    version: '1.0.1',
    packageVersion: '1.0.1',
    contentVersion: 1,
    isPublished: true,
    isFeatured: false,
    isNew: false,
    downloadSize: '1.1 MB',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516116211223-48a12725836c?auto=format&fit=crop&w=400&q=80',
    iconUrl: 'https://images.unsplash.com/photo-1516116211223-48a12725836c?auto=format&fit=crop&w=120&q=80',
    isDownloaded: false,
  },
  {
    gameId: 'candy-crush-land',
    slug: 'candy-crush-land',
    title: 'Candy Kingdom',
    description: 'Embark on a sugary sweet match-3 saga across 5 challenging candy levels!',
    category: 'Match-3',
    engineType: 'match-3',
    version: '1.3.0',
    packageVersion: '1.3.0',
    contentVersion: 3,
    isPublished: true,
    isFeatured: true,
    isNew: true,
    downloadSize: '2.6 MB',
    thumbnailUrl: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?auto=format&fit=crop&w=400&q=80',
    iconUrl: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?auto=format&fit=crop&w=120&q=80',
    isDownloaded: false,
  },
  {
    gameId: 'gem-match-legend',
    slug: 'gem-match-legend',
    title: 'Gem Match Legend',
    description: 'Match sparkling diamonds, rubies, and emeralds in ancient temple ruins!',
    category: 'Match-3',
    engineType: 'match-3',
    version: '1.0.0',
    packageVersion: '1.0.0',
    contentVersion: 1,
    isPublished: true,
    isFeatured: false,
    isNew: true,
    downloadSize: '2.0 MB',
    thumbnailUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=400&q=80',
    iconUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=120&q=80',
    isDownloaded: false,
  },
  {
    gameId: 'picture-puzzle-pro',
    slug: 'picture-puzzle-pro',
    title: 'Picture Grid Pro',
    description: 'Solve brain-bending 3x3 and 4x4 image sliding puzzles with step tracking!',
    category: 'Brain',
    engineType: 'puzzle',
    version: '1.1.0',
    packageVersion: '1.1.0',
    contentVersion: 2,
    isPublished: true,
    isFeatured: false,
    isNew: false,
    downloadSize: '1.5 MB',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=400&q=80',
    iconUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=120&q=80',
    isDownloaded: false,
  },
  {
    gameId: 'bubble-blast-mania',
    slug: 'bubble-blast-mania',
    title: 'Bubble Blast Mania',
    description: 'Hyper-casual bubble shooter with fast popping gameplay and neon visuals!',
    category: 'Arcade',
    engineType: 'bubble-shooter',
    version: '1.0.2',
    packageVersion: '1.0.2',
    contentVersion: 2,
    isPublished: true,
    isFeatured: true,
    isNew: true,
    downloadSize: '2.2 MB',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=400&q=80',
    iconUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=120&q=80',
    isDownloaded: false,
  },
];

export const BUNDLED_CONTENT_PACKAGES: Record<string, any> = {
  'bubble-shooter': BUBBLE_SHOOTER_FALLBACK_PACKAGE,
  'sweet-garden': SWEET_GARDEN_FALLBACK_PACKAGE,
  'sliding-puzzle': SLIDING_PUZZLE_FALLBACK_PACKAGE,
};
